### ISSUE TITLE
AstroNvim documentation inclusion

### ISSUE THREAD

**Issue by mehalter** [datamonsterr/astrovim_config#1]
Hey, I'm one of the AstroNvim developers and I am looking around for cool and built out user configurations to showcase on the documentation. Would you mind if I included a link to your configuration here: https://astronvim.github.io/recipes/black_belt ?

**Comment by datamonsterr** [comment]
@mehalter Haha the reason I used my approach is I didn't know the `without init.lua` method. I've just moved to this method but still leave a branch to be appropriate with your description on the web

**Comment by mehalter** [comment]
Awesome, thanks so much :)
